# Shiny Dashboard Template for Meta-Analysis Visualization
# This script is a template that will be copied and modified by the Dissemination Engine.

library(shiny)
library(shinythemes)

# --- UI Definition ---
ui <- fluidPage(
  theme = shinytheme("cerulean"),
  
  # Application title
  titlePanel("Meta-Analysis Results Explorer"),
  
  # Sidebar layout (optional, but good for structure)
  sidebarLayout(
    sidebarPanel(
      h4("About This Analysis"),
      p("This dashboard visualizes the results of a multi-study meta-analysis examining the relationship between Body Mass Index (BMI) and body fat percentage."),
      hr(),
      h5("Data Sources"),
      p("Data were harmonized from multiple studies, including NHANES and the UK Biobank."),
      hr(),
      p("This dashboard was automatically generated by the Dissemination Engine.")
    ),
    
    # Main panel for displaying outputs
    mainPanel(
      h3("Forest Plot of Correlations"),
      p("The plot below shows the estimated correlation from each study, along with the overall pooled estimate from the random-effects model."),
      imageOutput("forestPlot")
    )
  )
)

# --- Server Logic ---
server <- function(input, output) {
  
  output$forestPlot <- renderImage({
    # The path to the plot will be relative to the dashboard's directory.
    # The Dissemination Engine will place the plot here.
    plot_path <- "meta_analysis_forest_plot.png"
    
    # Return a list containing the filename
    list(
      src = plot_path,
      contentType = "image/png",
      width = "100%",
      height = "auto",
      alt = "Meta-analysis forest plot"
    )
  }, deleteFile = FALSE) # Important: Do not let Shiny delete the source image
  
}

# --- Run Application ---
shinyApp(ui = ui, server = server)
